### ISSUE TITLE
`let` expressions in this position are unstable

### ISSUE THREAD

**Issue by cwoolum** [pulse-loop/bluedroid#2]
Hi, 

Not sure if you're at the point where you're taking bug reports and feedback yet but wanted to get an issue in just in case. I am trying to use the crate and on `cargo build`, I get a lot of errors similar to 

```
error[E0658]: `let` expressions in this position are unstable
  --> C:\Users\slick\.cargo\registry\src\github.com-1ecc6299db9ec823\bluedroid-0.2.0\src\gatt_server\characteristic.rs:89:12
   |
89 |         if let AttributeControl::AutomaticResponse(_) = self.control && self.internal_value.is_empty() {
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
   = help: add `#![feature(let_chains)]` to the crate attributes to enable

error[E0658]: `let` expressions in this position are unstable
   --> C:\Users\slick\.cargo\registry\src\github.com-1ecc6299db9ec823\bluedroid-0.2.0\src\gatt_server\gatts_event_handler.rs:121:20
    |
121 |                 if let Some(profile) = self.get_profile(gatts_if) &&
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
    = help: add `#![feature(let_chains)]` to the crate attributes to enable

error[E0658]: `let` expressions in this position are unstable
   --> C:\Users\slick\.cargo\registry\src\github.com-1ecc6299db9ec823\bluedroid-0.2.0\src\gatt_server\gatts_event_handler.rs:122:20
    |
122 |                    let Some(service) = profile.read().unwrap().get_service(param.srvc_handle) &&
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
    = help: add `#![feature(let_chains)]` to the crate attributes to enable
```

I'm on `rustc 1.66.0-nightly (f5fed93ba 2022-09-27)`

**Comment by persello** [comment]
Should be fixed in next release. I was using a version of the compiler where this feature was stabilised, but it has been removed afterwards. The `develop` branch _might_ compile.

**Comment by persello** [comment]
Releasing v0.3.0 now.

**Comment by cwoolum** [comment]
I just gave `0.3.0` a try and I'm still getting the same error messages.

**Comment by cwoolum** [comment]
Adding `#![feature(let_chains)]` to `src/lib.rs` fixes the error.

**Comment by persello** [comment]
Ok, I confused some branches. I solved this issue in another branch that I haven't merged yet. As you can see, I have specified an old tool chain in `rust-toolchain.toml`. It should be fixed on the stable branch as soon as I merge PR #1, where I use a newer toolchain.
I don't think it'll take long, but enabling that feature is the quickest fix as of now. I'll update you when I merge, and release v0.3.1.

**Comment by persello** [comment]
I merged that pull request to the `develop` branch, and I can compile it with the 2022-10-30 `riscv32imc-esp-espidf` toolchain. If you can confirm that it works, I’m going to release v0.3.1.

**Comment by cwoolum** [comment]
Confirmed that I am able to compile with the `develop` branch. Thanks!

**Comment by persello** [comment]
0.3.1 released on cargo with this fix and ESP32 support.
